# Site settings
title: Vadym Markov
description: Vadym Markov. iOS Software Engineer.
keywords: Software,Development,OpenSource,Mobile,Swift,iOS,tvOS,watchOS
google-analytics: UA-116693063-1

# User settings
full_name: Vadym Markov
occupation: Software Engineer
email: markov.vadym@gmail.com
github_url: https://github.com/vadymmarkov
medium_url: https://medium.com/@vadymmarkov
twitter_url: https://twitter.com/vadymmarkov
linkedin_url: https://www.linkedin.com/in/vadymmarkov

# Build settings

assets:
  source_maps: false
  compression: true

exclude:
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
  - vendor
